try {
    try {
        a = 10 / 0;
        printd(a);
    } catch (DivisionByZero) {
        printe("Caught inner division by zero exception");
    }
    a = 10 / 2;
    printd(a);
} catch (DivisionByZero) {
    printe("Caught outer division by zero exception");
}