try {
    printd(5 * 5);
} catch (DivisionByZero) {
    prints("Caught division by zero exception");
}