try {
    a = 5 * 5;
    printd(a);
} catch (DivisionByZero) {
    printe("Caught division by zero exception");
}